# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InterfaceCatchment
                                 A QGIS plugin
 description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-13
        copyright            : (C) 2018 by Ivan Majic
        email                : imajicos@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InterfaceCatchment class from file InterfaceCatchment.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .interface_catchment import InterfaceCatchment
    return InterfaceCatchment(iface)
